CoDebt/CoDebt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

CoDebt/core/urls.py
from re import template
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name='home'),
    path('register/school/', views.register_school, name='register_school'),
    path('register/guardian/', views.register_users, name='register_guardian'),
    path('accounts/login/', views.login_user, name='login'),
    path('accounts/logout/', views.logout_user, name='logout'),
    path('contact/', views.contact_us, name='contact'),
    path('about/', views.about_us, name='about'),
    path('my-dashboard/', views.dashboard, name='dashboard'),
    path('students/profiles/<str:pk>/', views.studentprofile, name='profile'),
    path('schools/profiles/<str:pk>/', views.schoolprofiles, name='school_profile'),
    path('search/', views.search, name='search'),
    path('search/<str:pk>/', views.resolve, name='resolve'),
#     path('dashboard/', views.guardian_dashboard, name='guardian_dashboard'),
#     # path('testimonials/', views.testimonials, name='testimonials'),
     path('debtors/add/', views.add_debtor, name='add_debtor')
 ]

CoDebt/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from core.managers import CustomUserManager, SoftDeleteManager
from django.conf import settings
from cloudinary.models import CloudinaryField
from django.core.checks.messages import Error
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator

# Create your models here.
class SoftDeleteModel(models.Model):
    is_deleted = models.BooleanField(default=False)

    all_objects = models.Manager()
    objects = SoftDeleteManager()

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def restore(self):
        self.is_deleted = False
        self.save()

    def delete(self):
        raise Error()

    class Meta:
        abstract = True

class CustomUser(AbstractUser):
    username = None
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True, verbose_name='Email Address', max_length=255)
    is_school_admin = models.BooleanField(default=False)
    is_guardian = models.BooleanField(default=False)
    #avatar = models.ImageField(upload_to='avatar/', default='avatar.svg')
    avatar = CloudinaryField('avatars')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()

    class Meta:
        ordering = ["-email"]
        verbose_name = 'User'

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

class SchoolDetail(models.Model):
    school = models.OneToOneField(settings.AUTH_USER_MODEL, limit_choices_to={'is_school_admin':True}, on_delete=models.CASCADE)
    school_name = models.CharField(max_length=50)
    # copy_of_CAC = models.FileField(upload_to='proof_of_cac/')
    # copy_of_CAC = CloudinaryField('proof_of_CAC', null=True, blank=True)
    CAC_number = models.CharField(
        unique=True,
        max_length=10,
        validators=[MinLengthValidator(10, 'CAC Number must be 10 digits')]
    )
    
    def __str__(self):
        return self.school_name


class Debtor(SoftDeleteModel):
    posted_by = models.ForeignKey(SchoolDetail, on_delete=models.CASCADE, related_name='school_admin')
    guardian = models.OneToOneField(settings.AUTH_USER_MODEL, limit_choices_to={'is_guardian':True}, on_delete=models.SET_NULL, related_name='guardian', null=True, default=None)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    current_class = models.CharField(max_length=3)
    student_id = models.CharField(max_length=20, unique=True)
    address = models.CharField(max_length=100)
    debt_type = models.CharField(max_length=50)
    gender = models.CharField(max_length=1)
    outstanding_fees = models.PositiveIntegerField()
    is_contending_debt = models.BooleanField(default=False)
    age = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(5),
            MaxValueValidator(25)]
        )
    academic_session = models.CharField(max_length=10)
    #student_picture = models.ImageField(upload_to='student/')
    student_picture = CloudinaryField('student_pictures', null=True, blank=True)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Comment(models.Model):
    user_commenting = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    commented_on = models.ForeignKey(Debtor, on_delete=models.CASCADE)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment[:50]


class Contention(models.Model):
    guardian_contending = models.ForeignKey(settings.AUTH_USER_MODEL, limit_choices_to={'is_guardian':True}, on_delete=models.CASCADE)
    reason = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    #evidence = models.FileField(upload_to='proof_of_contention/')
    evidence = CloudinaryField('proof_of_contention')

    def __str__(self):
        return self.reason[:50]

CoDebt/core/forms.py
from django import forms
from django.contrib.auth. forms import UserCreationForm
from .models import CustomUser, SchoolDetail, Debtor


class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['first_name','last_name','email','password1','password2']
        widgets = {
            'first_name': forms.TextInput(attrs={'required':'required', 'placeholder': 'Enter your First Name here'}),
            'last_name': forms.TextInput(attrs={'required':'required', 'placeholder': 'Enter your Last Name here'}),
            'email': forms.EmailInput(attrs={'required':'required', 'placeholder': 'Enter your Email Address'}),
            'password1': forms.PasswordInput(attrs={'required':'required', 'placeholder': 'Create a password', 'data-toggle':'password1'}),
            'password2': forms.PasswordInput(attrs={'required':'required', 'placeholder': 'Confirm your password'})
        }
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name'
        }

class SchoolRegistration(forms.ModelForm):
    class Meta:
        model = SchoolDetail
        fields = ('school_name','CAC_number')
        widgets = {
            # 'copy_of_CAC':forms.FileInput(attrs={'id':'my-file','required':'required'})
        }
        labels ={
            # 'copy_of_CAC': 'Copy Of CAC',
            'school_name': 'School Name',
            'CAC_number': 'CAC Number'
        }

class DebtorForm(forms.ModelForm):
    class Meta:
        model = Debtor
        fields =  ['first_name', 'last_name', 'student_id', 'current_class', 'age', 'gender', 'academic_session', 'address', 'debt_type', 'student_picture', 'outstanding_fees']
        widgets = {
            'first_name': forms.TextInput(attrs={'required':'required', 'placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'required':'required', 'placeholder': 'Last Name'}),
            'student_id': forms.TextInput(attrs={'required':'required', 'placeholder': 'Student ID'}),
            'current_class': forms.TextInput(attrs={'required':'required', 'placeholder': 'Class'}),
            'age': forms.NumberInput(attrs={'required':'required', 'placeholder': 'Age'}),
            'gender': forms.TextInput(attrs={'required':'required', 'placeholder': 'M/F'}),
            'academic_session': forms.TextInput(attrs={'required':'required', 'placeholder': 'Academic Session'}),
            'address': forms.TextInput(attrs={'required':'required', 'placeholder': 'Address'}),
            'debt_type': forms.TextInput(attrs={'required':'required', 'placeholder': 'Nature of debt(School Fees, Books etc.)'}),
            'student_picture': forms.FileInput(attrs={'required':'required',}),
            'outstanding_fees': forms.NumberInput(attrs={'required':'required', 'placeholder': 'Amount Owed'}),
        }
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'student_id':'Student ID',
            'current_class':'Class',
            'age':'Age',
            'gender':'Gender',
            'academic_session':'Academic Session',
            'debt_type':'Payment For',
            'address':'Address',
            'student_picture':'Student Image',
            'outstanding_fees':'Outstanding Debt'
        }

CoDebt/core/views.py
from curses import ACS_GEQUAL
from django.db.models import Q
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import SchoolDetail, Debtor
from .forms import RegistrationForm, SchoolRegistration, ContactForm, DebtorForm
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import FormView

# Create your views here.

def index(request):
    return render(request, 'core/index.html')

def email_sender(user):
    subject = 'We are glad to have you at CoDebt'
    recipient_list = [user.email,]
    email_from = settings.EMAIL_HOST_USER
    content = f'Hi {user}. Thank you for signing up on CoDebt. We promise to help you recover your debts easily and promptly. Cheers'

    send_mail(subject, content, email_from, recipient_list)

def register_users(request):
    form = RegistrationForm()
    ctx ={'form': form}
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_guardian = True
            email_sender(user)
            user.save()
            return redirect('core:home')
        else:
            messages.info(request, 'An error occured, Please retry')
    return render(request, 'core/register-guardian.html', ctx)

def register_school(request):
    form = RegistrationForm()
    school_form = SchoolRegistration()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        school_form = SchoolRegistration(request.POST)
        if form.is_valid() and school_form.is_valid():
            user = form.save(commit=False)
            user.is_school_admin = True
            email_sender(user)
            user.save()
            SchoolDetail.objects.create(
                school=user,
                school_name=request.POST.get('school_name'),
                CAC_number=request.POST['CAC_number'],
            )
            return redirect('core:login')
        else:
            messages.error(request, 'An error occurred during registration, Please try again')
    ctx = {'form':form, 'school_form':school_form}
    return render(request, 'core/register-school.html',ctx)

def login_user(request):
    if request.user.is_authenticated:
        return redirect('core:home')

    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = authenticate(email=email, password=password)

        if user is not None:
            login(request, user)
            if user.is_school_admin:
                return redirect('core:dashboard')
            return redirect('core:home')
        
        messages.info(request, 'Invalid credentials')
        return redirect('core:login')    
    return render(request, 'core/login.html')


def logout_user(request):
    if not request.user.is_authenticated:
        messages.info(request, 'You are not signed in')
        return redirect('core:home')

    logout(request)
    messages.success(request, 'You have successfully signed out')
    return redirect('core:login')

def contact_us(request):
    return render(request, 'core/contact.html')

def about_us(request):
    return render(request, 'core/about-us.html')

@login_required()
def dashboard(request):
    user = request.user
    if not request.user.is_school_admin:
        messages.info(request, 'Only school admins can access here!')
        return redirect('core:home')
    all_time_debt = Debtor.all_objects.all().count()
    all_time_debt = all_time_debt if all_time_debt > 0 else 1
    school = SchoolDetail.objects.get(school=user.id)
    recovered_debts = Debtor.all_objects.filter(posted_by=school, is_deleted=True).count()
    debt_count = Debtor.objects.filter(posted_by=school).count()

    recovered_percent = (recovered_debts * 100) / all_time_debt
    indebted_percent = (debt_count * 100) / all_time_debt
    form = DebtorForm()
    ctx = {
        'user':user,
        'count': debt_count,
        'indebted_percent': indebted_percent,
        'recovered': recovered_debts,
        'recovered_percent': recovered_percent,
        'form': form,
        }
    return render(request, 'core/admin-dashboard.html',ctx)

# def guardiandashboard(request):
#     user = request.user
#     if not request.user.is_guardian:
#         messages.info(request, 'Only guardians can access here!')
#         return redirect('core:home')
#     school = Debtor.objects.get(posted_by=school)
#     student_ID = Debtor.objects.filter(student_id=user.student_id)
#     student_class = Debtor.objects.get()
#     age = Debtor.objects.get(age=user.age)
#     school = SchoolDetail.objects.get(school=user.id)
#     ctx = {
#         'Student ID': student_ID,
#         'Class': student_class,
#         'Age': age,
#         'Current School': school
#     } 
#     return render(request, 'core/guardiandashboard.html', ctx)

def studentprofile(request, pk):
    student = Debtor.objects.get(id=pk)

    ctx = {
        'school': student.posted_by,
        'student': student,
    }
    return render(request, 'core/studentprofile.html', ctx)

def schoolprofiles(request, pk):
    school = SchoolDetail.objects.get(id=pk)
    school_admin = school.school
    ctx = {
        'school':school,
        'school_admin': school_admin
    }
    return render(request, 'core/adminprofile.html', ctx)

def search(request):
    q = request.GET.get('q') if request.GET.get('q') else ''
    debtors = Debtor.objects.filter(
        Q(first_name__icontains=q) |
        Q(last_name__icontains=q) |
        Q(student_id__icontains=q)
    )
    school = SchoolDetail.objects.get(school=request.user)

    ctx = {'debtors': debtors, 'school':school}
    return render(request,'core/debtor-list.html', ctx)

def add_debtor(request):
    if request.method == 'POST':
     form = DebtorForm(request.POST)
     if form.is_valid():
        debtor = form.save(commit=False)
        debtor.posted_by = SchoolDetail.objects.get(school=request.user)
        debtor.save()
        messages.success(request, 'Debtor add successful')
    else:
        messages.info(request, 'Invalid Input')
    return redirect('core:dashboard')

def resolve(request, pk):
    debtor = Debtor.objects.get(id=pk)
    debtor.soft_delete()
    return redirect('core:search')

CoDebt/core/templates/core/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CoDebt</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
{#        <label>#}
{#            <textarea rows="4" cols="50" name="comment" form="usrform" placeholder="Enter text here...">#}
{#            </textarea>#}
{#        </label>#}
{#        <br>#}
{#        <form action="" id="usrform">#}
{#          Name: <input type="text" name="username" >#}
{#          Post: <input type="number" name="post" >#}
{#          <input type="submit">#}
{#        </form>#}
    </div>
</body>

CoDebt/core/templates/core/contact.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
<title>Contact Us</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    
    <script src="https://kit.fontawesome.com/f1061e8afa.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'styles/contact.css' %}">
{% endblock head %}
{% block navbar %}{% include 'navbar.html' %}{% endblock navbar %}
{% block content %}
    <main>
        <section class="cntact-bg-image">
            <div class="header-img" style="background-image: url('{% static 'images/bgcntct1.png' %}');">

            </div>

              </section class="contact-team ">

              <section class="contact-info">
                <div class="contct-heading2">
                    <p class="help-details">We are here to help and answer any questions you might have, we look forward to hearing from you</p>
                </div>
            </section>
            <section class="debtor-locate-section">
                <div class="locate-debtor1">
                    <h2>Trying to Locate a debtor</h2>
                </div>
                <div class="debtor-locator2">
                    <div class="email-client">
                        <p class="icons"> <img src="{% static 'images/message.jpg' %}" alt="message-icon" class="icon-contact"></p>
                        <!-- <h3>Email our Client Success team</h3> -->
                        <p class="contact-text">info@codebt.com</p>
    
                    </div>
                    <div class="check-guide">
                        <p class="icons"> <img src="{% static 'images/phone.jpg' %}" alt="phone-icon" class="icon-contact"></p>
                        <!-- <h3>Check out our help guide</h3> -->
                        <p class="contact-text">+23470392015</p>
                    </div>
                    <div class="check-guide">
                      <p class="icons"> <img src="{% static 'images/globe.jpg' %}" alt="globe-icon" class="icon-contact"></p>
                      <!-- <h3>Check out our help guide</h3> -->
                      <p class="contact-text">Check our help guide</p>
                  </div>
                </div>
            </section>
        <!-- <section>
            <div class="contct-heading2">
                <h2>Contact the Codebt Team</h2>
            </div>
            <div class="cntct-form">
                <form method="post", action="">
                    <div class="row">
                        <div class="col-6">
                            <label for="Fullname" class="form-label">Fullname</label>
                            <input type="text" class="form-control" id="fullname">
                        </div>
                        <div class="col-6">
                            <label for="name of school" class="form-label">Name of school</label>
                            <input type="text" class="form-control" id="schoolname">
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-6">
                            <label for="email" class="form-label">Email address</label>
                            <input type="email" class="form-control" id="email">
                        </div>
                        <div class="col-6">
                            <label for="exampleInputPassword1" class="form-label">Password</label>
                            <input type="password" class="form-control" id="exampleInputPassword1">
                        </div>

                    </div>

                    <div class="mb-3"></div>
                        <textarea class="form-control" id="Textarea1" rows="3"> Comment</textarea>
                </div>
                    <button type="submit" class="btn btn-primary contact-btn">Contact Us</button>
                </form>
            </div>
        </section>
        <section class="debtor-locate-section">
            <div class="locate-debtor1">
                <h2>Trying to Locate a debtor</h2>
            </div>
            <div class="debtor-locator2">
                <div class="email-client">
                    <p class="icons"><i class="fa-regular fa-envelope icon-contact"></i></i></p>
                    <h3>Email our Client Success team</h3>
                    <p class="contact-text">Do you have Questions? we will respond within 24hrs,please contact support@Codebt.com</p>

                </div>
                <div class="check-guide">
                    <p class="icons"><i class="fa-solid fa-globe icon-contact"></i></i></p>
                    <h3>Check out our help guide</h3>
                    <p class="contact-text">We have documentation for every aspect of the Codebt platform,you can see them here.</p>
                </div>
            </div>
        </section> -->
    </main>
    {% endblock content %}
    {% block footer %}{% include 'footer.html' %}{% endblock footer %}
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
    {% endblock scripts %}

CoDebt/core/templates/core/debtor-list.html
{% extends 'main.html' %} {% load static %} {% block head%}
<title>Debtors</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">


    <!-- Fonts links -->
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap"
        rel="stylesheet">

    <script src="https://kit.fontawesome.com/5d3fc22e6c.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'styles/debtor-list.css' %}">
{% endblock head %}
{% block content %}

{% include 'sidebar.html' %}
<div class="main">

    <!-- header section -->

    <div class="mobile-nav">
        <i class="fa-solid fa-bars" id="mham"></i>
        <img src="{% static 'images/CodebitLogo.jpg' %}" alt="logo">

        <div class="profile">
            <!-- <img src="./img/profile.png">
            <i class="fa-solid fa-angle-down"></i> -->
        </div>
    </div>


    <!-- Main body  -->
    <div class="body">
        <div class="search">
            <form action="{% url 'core:search' %}" method="get">
                <i class="fa-solid fa-magnifying-glass"></i>
                <input type="text" name="q" placeholder="Search by Student ID">
            </form>
        </div>
        {% if debtors %}
        <table>
            <tbody>
                {% for debtor in debtors %}

                <tr>
                    <td>
                        <img src="{% static 'images/profile.png' %}" alt="">
                        <span>{{debtor}}</span>
                    </td>
                    <td>
                        <span>
                            {{debtor.posted_by}}
                        </span>
                    </td>
                    <td>
                        <span>
                            {{debtor.debt}}
                        </span>
                    </td>
                    <td>
                        <span>
                            {{debtor.debt_type}}
                        </span>
                    </td>
                    <td>
                        <span>
                            &#x20A6;{{debtor.outstanding_fees}}
                        </span>
                    </td>
                    <td>
                        <a style="color: black;" href="{% url 'core:profile' debtor.id %}"><button class="deep">View Profile</button></a>
                    </td>
                    {% if school == debtor.posted_by %}
                    <td>
                        <a href="{% url 'core:resolve' debtor.id %}"><button class="deep">Resolve</button></a>
                    </td>
                    {% endif %}

                    {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h3>Fortunately, No debtors match your search. <br> The world would be better if we all paid our debts</h3>
{% endif %}
    </div>

</div>



</main>
{% endblock %}

CoDebt/core/templates/core/login.html
{% extends 'main.html' %} {% load static %} {% block head %}
<title>Sign In</title>
<!-- <link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
  crossorigin="anonymous"
/> -->
<link rel="stylesheet" href="{% static 'styles/login.css' %}" />
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
/>

{% endblock head %} {% block content %}

<section class="main-section">
  <header>
      <img src="{% static 'images/CoDebt.svg' %}" alt="">
  </header>
  <div>
    {% if messages %}
         {% for message in messages %}
              {% if message.tags == 'info'%}
                  <div class="alert alert-warning alert-dismissible fade show" role="alert">
                  <center><strong>{{ message}}</strong></center>
                  <button
                  style="..."
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"
                  ></button>
                  </div>
              {% else %}
                  <div class="alert alert-success alert-dismissible fade show">
                  <center><strong>{{message}}</strong></center>
                  <button style="..." type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>

              {% endif %}
          {% endfor %}    
      {% endif %}
  </div>
  <form method="post" class="form-section">
    {% csrf_token %}
      <div class="sign-in">
          <h1>Sign In</h1>
          <p>Sign in to recover pending debts</p>
      </div>
      <div class="email-pass">
          <label for="email">Email</label>
          <input type="email" name="email" id="email" placeholder="danieljames@gmail.com">
          <label for="password">Password</label>
          <input type="password" name="password" id="password" placeholder="**********">
          <span class="bi bi-eye-slash" id="togglePassword" style='color:black'></span>

          <button type="submit" id="submit">Sign in</button>
          <p>Don't have an account? <a href="{% url 'core:register_school' %}" id="signuplink"> Sign up</a></p>
      </div>
  </form>
</section>
{% endblock content %} {% block scripts %}
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
  crossorigin="anonymous"
></script>
<script src="{% static 'js/login.js' %}"></script>
{% endblock scripts %}