CoDebt/CoDebt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

CoDebt/core/urls.py
from re import template
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name='home'),
    path('register/school/', views.register_school, name='register_school'),
    path('register/guardian/', views.register_users, name='register_guardian'),
    path('accounts/login/', views.login_user, name='login'),
    path('accounts/logout/', views.logout_user, name='logout'),
    path('contact/', views.contact_us, name='contact'),
    path('about/', views.about_us, name='about'),
    path('my-dashboard/', views.dashboard, name='dashboard'),
    path('students/profiles/<str:pk>/', views.studentprofile, name='profile'),
    path('schools/profiles/<str:pk>/', views.schoolprofiles, name='school_profile'),
    path('search/', views.search, name='search'),
    path('search/<str:pk>/', views.resolve, name='resolve'),
#     path('dashboard/', views.guardian_dashboard, name='guardian_dashboard'),
#     # path('testimonials/', views.testimonials, name='testimonials'),
     path('debtors/add/', views.add_debtor, name='add_debtor')
 ]

CoDebt/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from core.managers import CustomUserManager, SoftDeleteManager
from django.conf import settings
from cloudinary.models import CloudinaryField
from django.core.checks.messages import Error
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator

# Create your models here.
class SoftDeleteModel(models.Model):
    is_deleted = models.BooleanField(default=False)

    all_objects = models.Manager()
    objects = SoftDeleteManager()

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def restore(self):
        self.is_deleted = False
        self.save()

    def delete(self):
        raise Error()

    class Meta:
        abstract = True

class CustomUser(AbstractUser):
    username = None
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True, verbose_name='Email Address', max_length=255)
    is_school_admin = models.BooleanField(default=False)
    is_guardian = models.BooleanField(default=False)
    #avatar = models.ImageField(upload_to='avatar/', default='avatar.svg')
    avatar = CloudinaryField('avatars')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()

    class Meta:
        ordering = ["-email"]
        verbose_name = 'User'

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

class SchoolDetail(models.Model):
    school = models.OneToOneField(settings.AUTH_USER_MODEL, limit_choices_to={'is_school_admin':True}, on_delete=models.CASCADE)
    school_name = models.CharField(max_length=50)
    # copy_of_CAC = models.FileField(upload_to='proof_of_cac/')
    # copy_of_CAC = CloudinaryField('proof_of_CAC', null=True, blank=True)
    CAC_number = models.CharField(
        unique=True,
        max_length=10,
        validators=[MinLengthValidator(10, 'CAC Number must be 10 digits')]
    )
    
    def __str__(self):
        return self.school_name


class Debtor(SoftDeleteModel):
    posted_by = models.ForeignKey(SchoolDetail, on_delete=models.CASCADE, related_name='school_admin')
    guardian = models.OneToOneField(settings.AUTH_USER_MODEL, limit_choices_to={'is_guardian':True}, on_delete=models.SET_NULL, related_name='guardian', null=True, default=None)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    current_class = models.CharField(max_length=3)
    student_id = models.CharField(max_length=20, unique=True)
    address = models.CharField(max_length=100)
    debt_type = models.CharField(max_length=50)
    gender = models.CharField(max_length=1)
    outstanding_fees = models.PositiveIntegerField()
    is_contending_debt = models.BooleanField(default=False)
    age = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(5),
            MaxValueValidator(25)]
        )
    academic_session = models.CharField(max_length=10)
    #student_picture = models.ImageField(upload_to='student/')
    student_picture = CloudinaryField('student_pictures', null=True, blank=True)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Comment(models.Model):
    user_commenting = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    commented_on = models.ForeignKey(Debtor, on_delete=models.CASCADE)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment[:50]


class Contention(models.Model):
    guardian_contending = models.ForeignKey(settings.AUTH_USER_MODEL, limit_choices_to={'is_guardian':True}, on_delete=models.CASCADE)
    reason = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    #evidence = models.FileField(upload_to='proof_of_contention/')
    evidence = CloudinaryField('proof_of_contention')

    def __str__(self):
        return self.reason[:50]

CoDebt/core/forms.py
from django import forms
from django.contrib.auth. forms import UserCreationForm
from .models import CustomUser, SchoolDetail, Debtor


class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['first_name','last_name','email','password1','password2']
        widgets = {
            'first_name': forms.TextInput(attrs={'required':'required', 'placeholder': 'Enter your First Name here'}),
            'last_name': forms.TextInput(attrs={'required':'required', 'placeholder': 'Enter your Last Name here'}),
            'email': forms.EmailInput(attrs={'required':'required', 'placeholder': 'Enter your Email Address'}),
            'password1': forms.PasswordInput(attrs={'required':'required', 'placeholder': 'Create a password', 'data-toggle':'password1'}),
            'password2': forms.PasswordInput(attrs={'required':'required', 'placeholder': 'Confirm your password'})
        }
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name'
        }

class SchoolRegistration(forms.ModelForm):
    class Meta:
        model = SchoolDetail
        fields = ('school_name','CAC_number')
        widgets = {
            # 'copy_of_CAC':forms.FileInput(attrs={'id':'my-file','required':'required'})
        }
        labels ={
            # 'copy_of_CAC': 'Copy Of CAC',
            'school_name': 'School Name',
            'CAC_number': 'CAC Number'
        }

class DebtorForm(forms.ModelForm):
    class Meta:
        model = Debtor
        fields =  ['first_name', 'last_name', 'student_id', 'current_class', 'age', 'gender', 'academic_session', 'address', 'debt_type', 'student_picture', 'outstanding_fees']
        widgets = {
            'first_name': forms.TextInput(attrs={'required':'required', 'placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'required':'required', 'placeholder': 'Last Name'}),
            'student_id': forms.TextInput(attrs={'required':'required', 'placeholder': 'Student ID'}),
            'current_class': forms.TextInput(attrs={'required':'required', 'placeholder': 'Class'}),
            'age': forms.NumberInput(attrs={'required':'required', 'placeholder': 'Age'}),
            'gender': forms.TextInput(attrs={'required':'required', 'placeholder': 'M/F'}),
            'academic_session': forms.TextInput(attrs={'required':'required', 'placeholder': 'Academic Session'}),
            'address': forms.TextInput(attrs={'required':'required', 'placeholder': 'Address'}),
            'debt_type': forms.TextInput(attrs={'required':'required', 'placeholder': 'Nature of debt(School Fees, Books etc.)'}),
            'student_picture': forms.FileInput(attrs={'required':'required',}),
            'outstanding_fees': forms.NumberInput(attrs={'required':'required', 'placeholder': 'Amount Owed'}),
        }
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'student_id':'Student ID',
            'current_class':'Class',
            'age':'Age',
            'gender':'Gender',
            'academic_session':'Academic Session',
            'debt_type':'Payment For',
            'address':'Address',
            'student_picture':'Student Image',
            'outstanding_fees':'Outstanding Debt'
        }

CoDebt/core/views.py
from curses import ACS_GEQUAL
from django.db.models import Q
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import SchoolDetail, Debtor
from .forms import RegistrationForm, SchoolRegistration, ContactForm, DebtorForm
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import FormView

# Create your views here.

def index(request):
    return render(request, 'core/index.html')

def email_sender(user):
    subject = 'We are glad to have you at CoDebt'
    recipient_list = [user.email,]
    email_from = settings.EMAIL_HOST_USER
    content = f'Hi {user}. Thank you for signing up on CoDebt. We promise to help you recover your debts easily and promptly. Cheers'

    send_mail(subject, content, email_from, recipient_list)

def register_users(request):
    form = RegistrationForm()
    ctx ={'form': form}
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_guardian = True
            email_sender(user)
            user.save()
            return redirect('core:home')
        else:
            messages.info(request, 'An error occured, Please retry')
    return render(request, 'core/register-guardian.html', ctx)

def register_school(request):
    form = RegistrationForm()
    school_form = SchoolRegistration()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        school_form = SchoolRegistration(request.POST)
        if form.is_valid() and school_form.is_valid():
            user = form.save(commit=False)
            user.is_school_admin = True
            email_sender(user)
            user.save()
            SchoolDetail.objects.create(
                school=user,
                school_name=request.POST.get('school_name'),
                CAC_number=request.POST['CAC_number'],
            )
            return redirect('core:login')
        else:
            messages.error(request, 'An error occurred during registration, Please try again')
    ctx = {'form':form, 'school_form':school_form}
    return render(request, 'core/register-school.html',ctx)

def login_user(request):
    if request.user.is_authenticated:
        return redirect('core:home')

    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = authenticate(email=email, password=password)

        if user is not None:
            login(request, user)
            if user.is_school_admin:
                return redirect('core:dashboard')
            return redirect('core:home')
        
        messages.info(request, 'Invalid credentials')
        return redirect('core:login')    
    return render(request, 'core/login.html')


def logout_user(request):
    if not request.user.is_authenticated:
        messages.info(request, 'You are not signed in')
        return redirect('core:home')

    logout(request)
    messages.success(request, 'You have successfully signed out')
    return redirect('core:login')

def contact_us(request):
    return render(request, 'core/contact.html')

def about_us(request):
    return render(request, 'core/about-us.html')

@login_required()
def dashboard(request):
    user = request.user
    if not request.user.is_school_admin:
        messages.info(request, 'Only school admins can access here!')
        return redirect('core:home')
    all_time_debt = Debtor.all_objects.all().count()
    all_time_debt = all_time_debt if all_time_debt > 0 else 1
    school = SchoolDetail.objects.get(school=user.id)
    recovered_debts = Debtor.all_objects.filter(posted_by=school, is_deleted=True).count()
    debt_count = Debtor.objects.filter(posted_by=school).count()

    recovered_percent = (recovered_debts * 100) / all_time_debt
    indebted_percent = (debt_count * 100) / all_time_debt
    form = DebtorForm()
    ctx = {
        'user':user,
        'count': debt_count,
        'indebted_percent': indebted_percent,
        'recovered': recovered_debts,
        'recovered_percent': recovered_percent,
        'form': form,
        }
    return render(request, 'core/admin-dashboard.html',ctx)

# def guardiandashboard(request):
#     user = request.user
#     if not request.user.is_guardian:
#         messages.info(request, 'Only guardians can access here!')
#         return redirect('core:home')
#     school = Debtor.objects.get(posted_by=school)
#     student_ID = Debtor.objects.filter(student_id=user.student_id)
#     student_class = Debtor.objects.get()
#     age = Debtor.objects.get(age=user.age)
#     school = SchoolDetail.objects.get(school=user.id)
#     ctx = {
#         'Student ID': student_ID,
#         'Class': student_class,
#         'Age': age,
#         'Current School': school
#     } 
#     return render(request, 'core/guardiandashboard.html', ctx)

def studentprofile(request, pk):
    student = Debtor.objects.get(id=pk)

    ctx = {
        'school': student.posted_by,
        'student': student,
    }
    return render(request, 'core/studentprofile.html', ctx)

def schoolprofiles(request, pk):
    school = SchoolDetail.objects.get(id=pk)
    school_admin = school.school
    ctx = {
        'school':school,
        'school_admin': school_admin
    }
    return render(request, 'core/adminprofile.html', ctx)

def search(request):
    q = request.GET.get('q') if request.GET.get('q') else ''
    debtors = Debtor.objects.filter(
        Q(first_name__icontains=q) |
        Q(last_name__icontains=q) |
        Q(student_id__icontains=q)
    )
    school = SchoolDetail.objects.get(school=request.user)

    ctx = {'debtors': debtors, 'school':school}
    return render(request,'core/debtor-list.html', ctx)

def add_debtor(request):
    if request.method == 'POST':
     form = DebtorForm(request.POST)
     if form.is_valid():
        debtor = form.save(commit=False)
        debtor.posted_by = SchoolDetail.objects.get(school=request.user)
        debtor.save()
        messages.success(request, 'Debtor add successful')
    else:
        messages.info(request, 'Invalid Input')
    return redirect('core:dashboard')

def resolve(request, pk):
    debtor = Debtor.objects.get(id=pk)
    debtor.soft_delete()
    return redirect('core:search')

CoDebt/core/templates/checkyourmail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/password_reset.css'%}">
    <title>Check-Your-mail</title>
</head>
<body>
    {% block content %}
    <header>
        <div class="header-image">
<img src="{% static 'images/header2 (2).png'%}" alt="Forgotten-password
">
        </div> 
    </header>
    <main>
        <div class="forgotten-main">
            <div class="inner-mail">
                <h2> Check Your Mail</h2>
                <p>A reset link has been sent to your mail  <a href="#">michaelHardy@gmail.com</a>  </p>
                <p>didn't recieve the email? <a href="{% url 'reset_password' %}"> click to resend Link</a></p>

            </div>
        </div>
        {% endblock content%}
    </main>
    
</body>
</html>

CoDebt/core/templates/confirmedpassword.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/password_reset.css'%}">
    <title>Confirmed Password</title>
</head>
<body>
    {% block content %}
    <header>
        <div class="header-image">
           <img src="{% static 'images/header2 (2).png'%}" alt="Forgotten-password
">
        </div>
    </header>
    <main>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="forgotten-main">
                <div class="Password-typemail">
                    <h2>Set new Password?</h2>
                </div>
                <div class="Forgotten-email">
                    <label for="Password" class="forgotten-label">Password</label>
                    <input type="password" id="password" class="email-forgotten-password">
                    <p>must be at least eight characters</p>
                </div>
            
                <div class="Forgotten-email">
                    <label for="email" class="forgotten-label">Confirmed Password</label>
                    <input type="email" placeholder="mailhardy@gmail.com" id="email" class="email-forgotten-password">
                </div>
                <button class="forgotten-btn">Reset Password</button>

            </div>
        </form>
        {% endblock content%} 
    </main>
    
</body>
</html>

CoDebt/core/templates/footer.html
{% load static %}
  <footer>
    <div class="container">
      <div class="subscribe">
        <h2>Subscribe to our News letter</h2>
        <p>Share your email and we will share our world</p>
        <form>
          <input type="email" placeholder="Email address" />
          <button>
            SUBMIT
          </button>
        </form>

      </div>

      <div class="footer-content">
        <img src="{% static 'images/logo.svg' %}" alt="logo" />
        <ul>
          <li>
            <b>Codebt</b>
          </li>
          <li>
            Services
          </li>
          <li>
            About us
          </li>
          <li>
            Contact us
          </li>
        </ul>

        <ul>
          <li>
            <b>Community</b>
          </li>
          <li>
            Blog
          </li>
          <li>
            Partners
          </li>
          <li>
            Administrators
          </li>
        </ul>

        <ul>
          <li>
            <b>Legal</b>
          </li>
          <li>
            Terms of service
          </li>
          <li>
            Privacy policy
          </li>
          <li>
            Cookie policy
          </li>
          <li>
            Help center
          </li>
        </ul>

      </div>

      <div class="copyright-socials">

        <ul class="social-media">
          <li>
            <a class="circle" href="#">
              <img src="{% static 'images/facebook.png' %}" alt="facebook" />
            </a>
          </li>
          <li>
            <a class="circle" href="#">
              <img src="{% static 'images/facebook.png' %}" alt="linkdein" />
            </a>
          </li>
          <li>
            <a href="#">
              <img src="{% static 'images/Twitter.svg' %}" alt="Twitter" />
            </a>
          </li>
          <li>
            <a class="circle" href="#">
              <img src="{% static 'images/Instagram.svg' %}" alt="Instagram" />
            </a>

          </li>
        </ul>

        <p>&copy; 2022 CoDebt Inc. All rights reserved.</p>

      </div>


    </div>

  </footer>

CoDebt/core/templates/forgottenpassword.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/password_reset.css'%}">
    <title>Paasword reset</title>
</head>
<body>
    {% block content %}
    <header>
        <div class="header-image">
<img src="{% static 'images/forgottenpassword-image.png' %}" alt="Forgotten-password
">
        </div>
    </header>
    <main>
        <div class="forgotten-main">
            <div class="Password-typemail">
                <h2>Forgotten Password?</h2>
                <p>No worries we will send you reset instruction</p>
            </div>
            <form method="POST" action="">
                {% csrf_token %}
                <div class="Forgotten-email">
                   <label for="email" class="forgotten-label">Email Address</label>
                    {{form.email}}
                </div>
            <button class="forgotten-btn">Reset Password</button>
            </form>
        </div>
        {% endblock content%}

    </main>
</body>
</html>

CoDebt/core/templates/guardian.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'styles/guardian.css'%}" />
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
</head>
<body>
    {% block content %} 
    
    <div class="container">
        <header>
            <div class="logo">
                <nav>
                    <img src="{% static 'images/CoDebt Logo.svg'%}" alt="logo" />
                </nav>
            </div> 
        </header>
        <img src="{% static 'images/rafiki.svg'%}" alt="rafiki" />
        <div class="content">
            
            <form method='POST'class="box" action="#">
                {% csrf_token %}
                <div class="title">Create An Account</div>
                <div class="user-details">
                    <div class="input-box">
                        <span class="details">First Name</span>
                        <input type="text" required>
                        {{form.first_name}}
                    </div>
                    <div class="input-box">
                        <span class="details">Last Name</span>
                        <input type="text" required>
                        {{form.last_name}}
                    </div>
                    <div class="input-box">
                        <span class="details">Status</span>
                        <select class="select">
                            <option disabled selected></option>
                            <option value="single">Single</option>
                            <option value="married">Married</option>
                            <option value="divorced">Divorced</option>
                            <option value="prefer not to say">Prefer not to say</option>
                        </select>
                    </div>
                    <div class="input-box">
                        <span class="details">Email Address</span>
                        <input type="text" required>
                        {{form.email}}
                    </div>
                    <div class="input-box">
                        <span class="details">Password</span>
                        <div class="toggle-eye open">
                            <ion-icon name="eye-outline"></ion-icon>
                            {{form.password1}}    
                        </div>
                        <input type="password" required>
                    </div>
                    <div class="input-box">
                        <span class="details">Confirm Password</span>
                        <div class="toggle-eye close">
                            <ion-icon name="eye-off-outline"></ion-icon>
                            {{form.password2}}
                        </div>
                        <input type="password" required>
                    </div>
                </div>
                <label class="checkbox" for="myCheckboxId">
                    <input class="checkbox__input" type="checkbox" name="myCheckboxName" id="myCheckboxId">
                    <div class="checkbox__box"></div>
                    <small>
                      I have read and agree with the<a href="#"> terms of Services</a> and <a href="#">privacy policy</a>
                    </small>
                  </label>
                <div class="btn">
                    <button class="button">Create Account</button>
                </div>
                
                <div class="last">
                    <small>
                        <strong>Already have an account?</strong>
                        <a href="#">Sign in</a>
                    </small>
                </div>
          </form>
        </div>
      </div>
      {% endblock content%}
</body>
</html>

CoDebt/core/templates/js-admin-dasboard.html
<script>
const yValues = [{{recovered}}, {{count}}];
const barColors = [
"#b91d47",
"#00aba9",
];

new Chart("myChart", {
type: "doughnut",
data: {
    datasets: [{
        backgroundColor: barColors,
        data: [yValues[0]+1, yValues[0]+1]
    }],
    labels:['Recovered', 'Indebted']
},
});
</script>

CoDebt/core/templates/main.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    {% block head %} {% endblock head %}
  </head>

  <body>
    {% block navbar %}{% endblock navbar %}
    {% block content %}{% endblock content %}
    {% block footer %}{% endblock footer %}

    {% block scripts %} {% endblock scripts %}
  </body>
</html>

CoDebt/core/templates/navbar.html
{% load static %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding: 1rem">
      <a class="navbar-brand" href="{% url 'core:home' %}">
        <img src="{% static 'images/CodebitLogo.jpg' %}" alt="Logo">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link hover-shadow" href="{% url 'core:home' %}">HOME </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link hover-shadow" href="{% url 'core:about' %}">ABOUT US</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link hover-shadow" href="{% url 'core:about' %}"> TESTIMONIALS</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link hover-overlay" href="{% url 'core:contact' %}">CONTACT US</a>
          </li>
        </ul>
        <div>
          {% if not request.user.is_authenticated %}
          <a href="{% url 'core:login' %}" class="btn btn-outline-primary">Login</a>
          {% else %}
          <a href="{% url 'core:logout' %}" class="btn btn-outline-primary">Logout</a>
          {% endif %}
          <!-- single dropdown button -->
          {% if not request.user.is_authenticated  %}
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              Sign Up
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'core:register_guardian' %}">As Guardian</a>
              <a class="dropdown-item" href="{% url 'core:register_school' %}">As School Admin</a>
            </div>
          </div>
          {% else %}
          <a href="{% url 'core:dashboard' %}" class="btn btn-outline-primary">My Account</a>
          {% endif %}
        </div>

      </div>
    </nav>

CoDebt/core/templates/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The CoDebt Team
{% endautoescape %}

CoDebt/core/templates/passwordreset.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/password_reset.css'%}">
    <title>Password reset </title>
</head>
<body>
    {% block content %}
    <header>
        <div class="header-image">
<img src="{% static 'images/header2 (2).png'%}" alt="Forgotten-password
">
        </div>
    </header>
    <main>
        <div class="forgotten-main">
            <div class="inner-mail2">
                <h2>Password reset</h2>
                <p>your Password has been successfully reset click below to login</p>
            </div>

            <button class="forgotten-btn">Continue</button>
        </div>
        {% endblock content%}

    </main>
    
</body>
</html>

CoDebt/core/templates/sidebar.html
{% load static %}
<div class="sidebar">
    <div class="container-fluid">
        <img src="{% static 'images/logo.svg' %}" alt="">
        <div class="side-nav">

            <div class="dashboard" id="active">
                <a href="{% url 'core:dashboard' %}"><i class="fa-solid fa-table-columns"></i><span>Dashboard</span></a>
            </div>

            <div class="debtors">
                <a href="{% url 'core:search' %}">
                    <i class="fa-solid fa-user-ninja"></i><span>Debtors</span>
                </a>
            </div>
            <!-- <div class="posts">
                <a href="">
                    <i class="fa-solid fa-indent"></i><span>Posts</span>
                </a>
            </div> -->
            <div class="contends">
                <a href="#">
                    <i class="fa-solid fa-message"></i><span>Contends</span>
                </a>
            </div>

            <div class="comments">
                <a href="#">
                    <i class="fa-solid fa-comments"></i><span>Comments</span>
                </a>
            </div>

            <div class="profile">
                <a href="#">
                    <i class="fa-solid fa-id-badge"></i><span>Profile</span>
                </a>
            </div>
        </div>
        <div class="support">
            <a href="#">
                <span>Get Support Now</span>
            </a>
        </div>
        <div class="logout">
            <a href="{% url 'core:logout' %}">
                <i class="fa-solid fa-right-from-bracket"></i><span>Logout</span>
            </a>
        </div>
    </div>

</div>